// Generated by psc-bundle 0.11.6
var PS = {};
(function(exports) {
    "use strict";

  exports.showIntImpl = function (n) {
    return n.toString();
  };

  exports.showStringImpl = function (s) {
    var l = s.length;
    return "\"" + s.replace(
      /[\0-\x1F\x7F"\\]/g, // eslint-disable-line no-control-regex
      function (c, i) {
        switch (c) {
          case "\"":
          case "\\":
            return "\\" + c;
          case "\x07": return "\\a";
          case "\b": return "\\b";
          case "\f": return "\\f";
          case "\n": return "\\n";
          case "\r": return "\\r";
          case "\t": return "\\t";
          case "\v": return "\\v";
        }
        var k = i + 1;
        var empty = k < l && s[k] >= "0" && s[k] <= "9" ? "\\&" : "";
        return "\\" + c.charCodeAt(0).toString(10) + empty;
      }
    ) + "\"";
  };
})(PS["Data.Show"] = PS["Data.Show"] || {});
(function(exports) {
  // Generated by purs version 0.11.6
  "use strict";
  var $foreign = PS["Data.Show"];     
  var Show = function (show) {
      this.show = show;
  };
  var showString = new Show($foreign.showStringImpl);
  var showInt = new Show($foreign.showIntImpl);
  var show = function (dict) {
      return dict.show;
  };
  exports["Show"] = Show;
  exports["show"] = show;
  exports["showInt"] = showInt;
  exports["showString"] = showString;
})(PS["Data.Show"] = PS["Data.Show"] || {});
(function(exports) {
  // Generated by purs version 0.11.6
  "use strict";
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Show = PS["Data.Show"];
  var Prelude = PS["Prelude"];        
  var T1 = (function () {
      function T1(value0) {
          this.value0 = value0;
      };
      T1.create = function (value0) {
          return new T1(value0);
      };
      return T1;
  })();
  var T2 = (function () {
      function T2(value0) {
          this.value0 = value0;
      };
      T2.create = function (value0) {
          return new T2(value0);
      };
      return T2;
  })();
  var showMyAdt = function (v) {
      if (v instanceof T1) {
          return "(T1 " + (Data_Show.show(Data_Show.showInt)(v.value0) + ")");
      };
      if (v instanceof T2) {
          return "(T2 " + (Data_Show.show(Data_Show.showString)(v.value0) + ")");
      };
      throw new Error("Failed pattern match at Main line 9, column 1 - line 9, column 29: " + [ v.constructor.name ]);
  };
  exports["T1"] = T1;
  exports["T2"] = T2;
  exports["showMyAdt"] = showMyAdt;
})(PS["Main"] = PS["Main"] || {});
PS["Main"].main();
